export const errorStartSession = "Error al iniciar sesión";
export const requestError = "Error en la solicitud";
export const getUsersError = "Error al obtener usuarios";
export const getMessagesError = "Error al obtener mensajes";
export const reloadMessagesError = "Error al recargar mensajes";
export const sendMessagesError = "Error al enviar mensaje";
export const validateUsernameError = "El nombre de usuario debe tener al menos 3 letras, sin mayúsculas ni caracteres especiales, y los números deben estar al final."
export const validatePasswordError = "La contraseña debe tener al menos 6 caracteres.";
export const loginError = "Error al intentar iniciar sesión.";
export const errorFetchingMessages = "Error fetching messages";
export const errorChangingMessageState = "Error cambiando el estado del mensaje";
export const createGroupError = "Error al crear el grupo"
export const nameGroupError = "El nombre del grupo es obligatorio."
export const openChatError = "Error cargando openChat.html."
export const loadingGroupForm = "Error al cargar el formulario de creación de grupo"
export const getUsersForGroupsError = "Error al cargar usuarios para crear el grupo"
export const backgroundSelectionError = "Error al seleccionar el fondo"
export const loadingGroupOptionsError = "Error al cargar las opciones de grupo" 
export const groupIdError = "Error al obtener el id del grupo"
export const saveGroupChangesError = "Error al guardar los cambios del grupo"
export const getGroupInfoError = "Error al obtener la información del grupo"
export const updateGroupError = "Error al actualizar el grupo"
export const removeUserError = "Error al remover usuario"